### PR TITLE
Build render list method

### PR DESCRIPTION
**Pull request by rouzier**

### CODE REVIEW

**Comment by abraxxa** [comment]
Why not just override the already existing builder method?

**Comment by rouzier** [comment]
This would require me to create a new Block module every time I want to build a new block.

**Comment by abraxxa** [comment]
Can you give an example for what you call 'block module'?

**Comment by rouzier** [comment]
In order to have a dynamic render_list I would need to create a new Block Widget.
I want to avoid doing that

Here are is an example with and out build_render_list_method

Without
 
```
{
package BlockTest;
use Moose;
extends 'HTML::FormHandler::Widget::Block';
sub build_render_list { [qw(f1)] }
}

{
package FormTest;
use HTML::FormHandler::Moose;
has_field f1 => ( type => 'Text');

has_block test => (
    type => 'BlockTest',
);
}
```

With
```
{
package FormTest2;
use HTML::FormHandler::Moose;
has_field f1 => ( type => 'Text');

has_block test => (
    build_render_list_method => sub { [qw(f1)] }
);
}
```

**Pull request merged**
