### PR TITLE
Enable strict and warnings for Kwalite metrcis

### PR DESCRIPTION
**Pull request by jluis**
Signed-off-by: Jose Luis Perez Diez <jluis@escomposlinux.org>

### CODE REVIEW

**Comment by abraxxa** [comment]
It seems you don't know that use Moose enables warnings and strict.

**Comment by jluis** [comment]
El Dijous 16 Juliol 2015, a les 05:52:35, Alexander Hartmaier va escriure:
> It seems you don't know that use Moose enables warnings and strict.

I know but it don't get reflected in the kwalite metrics see:

http://cpants.cpanauthors.org/dist/HTML-FormHandler

**Comment by abraxxa** [comment]
Then please submit a patch for cpants, working around it by adding thousands of lines to each module which uses one of the modules that enable strict and warnings is no good solution in my opinion.

**Comment by gshank** [comment]
As Abraxxa said, putting a bunch of unnecessary "use strict; use warnings;" into FormHandler is not the proper solution. The problem is with the Kwalitee metrics.

**Pull request closed without merging**
